# Usa una imagen base adecuada para ARM
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine-arm32v7 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine-arm32v7 AS build
WORKDIR /src
COPY ["apiCuentas/apiCuentas.csproj", "apiCuentas/"]
RUN dotnet restore "apiCuentas/apiCuentas.csproj"
COPY . .
WORKDIR "/src/apiCuentas"
RUN dotnet build "apiCuentas.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "apiCuentas.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "apiCuentas.dll"]
