version: '3.8'
services:
  apicuentas:
    build:
      context: .
      dockerfile: apiCuentas/dockerfile
    ports:
      - "8080:8080"  # Mapea el puerto del contenedor al puerto de tu máquina host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    secrets:
      - db_connection_string  

secrets:
  db_connection_string:
    external: true
